credentials:
  usernames:
    demo:
      email: demo.strtgy.ia
      name: Usuario Demo
      password: strtgy_2025
    arturo:
      email: arturo.strtgy.ia
      name: Arturo Salazar
      password: strtgy_2025
    fabian:
      email: fabian.strtgy.ia
      name: Fabian Salazar
      password: strtgy_2025
    gairo:
      email: gairo.strtgy.ia
      name: Gairo Peralta
      password: strtgy_2025
    christian:
      email: christian.strtgy.ia
      name: Christian Magallon
      password: strtgy_2025

cookie:
  expiry_days: 30
  key: "real_estate_chat_signature" 
  name: "real_estate_chat_cookie"