credentials:
  usernames:
    demo.strtgy.ai:
      email: demo.strtgy.ai
      name: Usuario Demo
      password: strtgy_2025
    arturo.strtgy.ai:
      email: arturo.strtgy.ai
      name: Arturo Salazar
      password: strtgy_2025
    fabian.strtgy.ai:
      email: fabian.strtgy.ai
      name: Fabián Salazar
      password: strtgy_2025
    gairo.strtgy.ai:
      email: gairo.strtgy.ai
      name: Gairo Peralta
      password: strtgy_2025
    christian.strtgy.ai:
      email: christian.strtgy.ai
      name: Christian Magallón
      password: strtgy_2025

cookie:
  expiry_days: 30
  key: strtgy_chat_signature
  name: strtgy_chat_cookie
