credentials:
  usernames:
    demo.raesa.ia:
      email: demo.raesa.ia
      name: Usuario Demo
      password: raesa_2025
    arturo.raesa.ia:
      email: arturo.raesa.ia
      name: Arturo Salazar
      password: raesa_2025
    fabian.raesa.ia:
      email: fabian.raesa.ia
      name: Fabián Salazar
      password: raesa_2025
    gairo.raesa.ia:
      email: gairo.raesa.ia
      name: Gairo Peralta
      password: raesa_2025
    christian.raesa.ia:
      email: christian.raesa.ia
      name: Christian Magallón
      password: raesa_2025

cookie:
  expiry_days: 30
  key: raesa_chat_signature
  name: raesa_chat_cookie