[theme]
primaryColor = "#1E3A8A"  # STRTGY blue
backgroundColor = "#FFFFFF"  # Pure white background
secondaryBackgroundColor = "#F8FAFC"  # Light gray for sidebar
textColor = "#1E293B"  # Dark gray for text
font = "sans serif"

[ui]
hideTopBar = true